### ISSUE TITLE
cyipopt throws KeyError when IPOPT exceeds `max_wall_time`

### ISSUE THREAD

**Issue by tobias-kies-artemis** [mechmotum/cyipopt#131]
# Example reproducing the issue
```python
# Basic example taken and shortened from
#   https://cyipopt.readthedocs.io/en/stable/tutorial.html#
import cyipopt
import numpy as np


class HS071:
    def objective(self, x):
        return x[0] * x[3] * np.sum(x[0:3]) + x[2]

    def gradient(self, x):
        return np.array(
            [
                x[0] * x[3] + x[3] * np.sum(x[0:3]),
                x[0] * x[3],
                x[0] * x[3] + 1.0,
                x[0] * np.sum(x[0:3]),
            ]
        )

    def constraints(self, x):
        return np.array((np.prod(x), np.dot(x, x)))

    def jacobian(self, x):
        return np.concatenate((np.prod(x) / x, 2 * x))

    def hessianstructure(self):
        return np.nonzero(np.tril(np.ones((4, 4))))

    def hessian(self, x, lagrange, obj_factor):
        H = obj_factor * np.array(
            (
                (2 * x[3], 0, 0, 0),
                (x[3], 0, 0, 0),
                (x[3], 0, 0, 0),
                (2 * x[0] + x[1] + x[2], x[0], x[0], 0),
            )
        )

        H += lagrange[0] * np.array(
            (
                (0, 0, 0, 0),
                (x[2] * x[3], 0, 0, 0),
                (x[1] * x[3], x[0] * x[3], 0, 0),
                (x[1] * x[2], x[0] * x[2], x[0] * x[1], 0),
            )
        )

        H += lagrange[1] * 2 * np.eye(4)

        row, col = self.hessianstructure()

        return H[row, col]


lb = [1.0, 1.0, 1.0, 1.0]
ub = [5.0, 5.0, 5.0, 5.0]

cl = [25.0, 40.0]
cu = [2.0e19, 40.0]

x0 = [1.0, 5.0, 5.0, 1.0]

nlp = cyipopt.Problem(
    n=len(x0),
    m=len(cl),
    problem_obj=HS071(),
    lb=lb,
    ub=ub,
    cl=cl,
    cu=cu,
)

nlp.add_option("print_level", 5)
nlp.add_option("max_wall_time", 0.01)

x, info = nlp.solve(x0)

```

# Output
```
******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit https://github.com/coin-or/Ipopt
******************************************************************************

This is Ipopt version 3.14.4, running with linear solver MUMPS 5.2.1.

Number of nonzeros in equality constraint Jacobian...:        4
Number of nonzeros in inequality constraint Jacobian.:        4
Number of nonzeros in Lagrangian Hessian.............:       10

Total number of variables............................:        4
                     variables with only lower bounds:        0
                variables with lower and upper bounds:        4
                     variables with only upper bounds:        0
Total number of equality constraints.................:        1
Total number of inequality constraints...............:        1
        inequality constraints with only lower bounds:        1
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  1.6109693e+01 1.12e+01 5.28e-01  -1.0 0.00e+00    -  0.00e+00 0.00e+00   0
   1  1.6982239e+01 7.30e-01 1.02e+01  -1.0 6.11e-01    -  7.19e-02 1.00e+00f  1
   2  1.7318411e+01 3.60e-02 5.05e-01  -1.0 1.61e-01    -  1.00e+00 1.00e+00h  1
   3  1.6849424e+01 2.78e-01 6.68e-02  -1.7 2.85e-01    -  7.94e-01 1.00e+00h  1

Number of Iterations....: 3

                                   (scaled)                 (unscaled)
Objective...............:   1.6849423718580880e+01    1.6849423718580880e+01
Dual infeasibility......:   6.6756651621447144e-02    6.6756651621447144e-02
Constraint violation....:   2.7823558763444467e-01    2.7823558763444467e-01
Variable bound violation:   0.0000000000000000e+00    0.0000000000000000e+00
Complementarity.........:   7.4835718157189646e-02    7.4835718157189646e-02
Overall NLP error.......:   2.7823558763444467e-01    2.7823558763444467e-01


Number of objective function evaluations             = 4
Number of objective gradient evaluations             = 4
Number of equality constraint evaluations            = 4
Number of inequality constraint evaluations          = 4
Number of equality constraint Jacobian evaluations   = 4
Number of inequality constraint Jacobian evaluations = 4
Number of Lagrangian Hessian evaluations             = 3
Total seconds in IPOPT                               = 0.012

EXIT: Maximum wallclock time exceeded.
Traceback (most recent call last):
  File "/home/tkies/src/projects/2021_10_first_nardo_laptime_simulations/cyipopt_example.py", line 77, in <module>
    x, info = nlp.solve(x0)
  File "cyipopt/cython/ipopt_wrapper.pyx", line 652, in ipopt_wrapper.Problem.solve
KeyError: -5
```

# Solution Proposals
* To solve the observed issue, we could add another line to [ipoppt_wrapper.pyx STATUS_MESSAGES](https://github.com/mechmotum/cyipopt/blob/168d24677f5d3249b42161c6e31823a225456d09/cyipopt/cython/ipopt_wrapper.pyx#L79). However, then we will still run against issues whenever IPOPT has a status code which is not (yet) known to cyipopt.
* Hence, in addition, I would propose to change the above-mentioned line [cyipopt/cython/ipopt_wrapper.pyx:652](https://github.com/mechmotum/cyipopt/blob/168d24677f5d3249b42161c6e31823a225456d09/cyipopt/cython/ipopt_wrapper.pyx#L652) to read `"status_msg": STATUS_MESSAGES.get(stat, b"Unknown status")` instead of `"status_msg": STATUS_MESSAGES[stat]` (or something along these lines). That way, `cyipopt` would fall back to setting the status message "Unknown status" whenever an unknown status is encountered instead of throwing a `KeyError` right away.

I took the liberty to create a [pull request here](https://github.com/mechmotum/cyipopt/pull/132) to illustrate my suggested changes directly in code.

**Comment by moorepants** [comment]
I don't get a key error when running this with master:

```
In [2]: %paste
# Basic example taken and shortened from
#   https://cyipopt.readthedocs.io/en/stable/tutorial.html#
import cyipopt
import numpy as np


class HS071:
    def objective(self, x):
        return x[0] * x[3] * np.sum(x[0:3]) + x[2]

    def gradient(self, x):
        return np.array(
            [
                x[0] * x[3] + x[3] * np.sum(x[0:3]),
                x[0] * x[3],
                x[0] * x[3] + 1.0,
                x[0] * np.sum(x[0:3]),
            ]
        )

    def constraints(self, x):
        return np.array((np.prod(x), np.dot(x, x)))

    def jacobian(self, x):
        return np.concatenate((np.prod(x) / x, 2 * x))

    def hessianstructure(self):
        return np.nonzero(np.tril(np.ones((4, 4))))

    def hessian(self, x, lagrange, obj_factor):
        H = obj_factor * np.array(
            (
                (2 * x[3], 0, 0, 0),
                (x[3], 0, 0, 0),
                (x[3], 0, 0, 0),
                (2 * x[0] + x[1] + x[2], x[0], x[0], 0),
            )
        )

        H += lagrange[0] * np.array(
            (
                (0, 0, 0, 0),
                (x[2] * x[3], 0, 0, 0),
                (x[1] * x[3], x[0] * x[3], 0, 0),
                (x[1] * x[2], x[0] * x[2], x[0] * x[1], 0),
            )
        )

        H += lagrange[1] * 2 * np.eye(4)

        row, col = self.hessianstructure()

        return H[row, col]


lb = [1.0, 1.0, 1.0, 1.0]
ub = [5.0, 5.0, 5.0, 5.0]

cl = [25.0, 40.0]
cu = [2.0e19, 40.0]

x0 = [1.0, 5.0, 5.0, 1.0]

nlp = cyipopt.Problem(
    n=len(x0),
    m=len(cl),
    problem_obj=HS071(),
    lb=lb,
    ub=ub,
    cl=cl,
    cu=cu,
)

nlp.add_option("print_level", 5)
nlp.add_option("max_wall_time", 0.01)

x, info = nlp.solve(x0)
## -- End pasted text --
This is Ipopt version 3.14.12, running with linear solver MUMPS 5.2.1.

Number of nonzeros in equality constraint Jacobian...:        4
Number of nonzeros in inequality constraint Jacobian.:        4
Number of nonzeros in Lagrangian Hessian.............:       10

Total number of variables............................:        4
                     variables with only lower bounds:        0
                variables with lower and upper bounds:        4
                     variables with only upper bounds:        0
Total number of equality constraints.................:        1
Total number of inequality constraints...............:        1
        inequality constraints with only lower bounds:        1
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  1.6109693e+01 1.12e+01 5.28e-01  -1.0 0.00e+00    -  0.00e+00 0.00e+00   0
   1  1.6982239e+01 7.30e-01 1.02e+01  -1.0 6.11e-01    -  7.19e-02 1.00e+00f  1
   2  1.7318411e+01 3.60e-02 5.05e-01  -1.0 1.61e-01    -  1.00e+00 1.00e+00h  1
   3  1.6849424e+01 2.78e-01 6.68e-02  -1.7 2.85e-01    -  7.94e-01 1.00e+00h  1
   4  1.7051199e+01 4.71e-03 2.78e-03  -1.7 6.06e-02    -  1.00e+00 1.00e+00h  1

Number of Iterations....: 4

                                   (scaled)                 (unscaled)
Objective...............:   1.7051198876333952e+01    1.7051198876333952e+01
Dual infeasibility......:   2.7825374152236852e-03    2.7825374152236852e-03
Constraint violation....:   4.7140386293236247e-03    4.7140386293236247e-03
Variable bound violation:   0.0000000000000000e+00    0.0000000000000000e+00
Complementarity.........:   2.1976083404794133e-02    2.1976083404794133e-02
Overall NLP error.......:   2.1976083404794133e-02    2.1976083404794133e-02


Number of objective function evaluations             = 5
Number of objective gradient evaluations             = 5
Number of equality constraint evaluations            = 5
Number of inequality constraint evaluations          = 5
Number of equality constraint Jacobian evaluations   = 5
Number of inequality constraint Jacobian evaluations = 5
Number of Lagrangian Hessian evaluations             = 4
Total seconds in IPOPT                               = 0.012

EXIT: Maximum wallclock time exceeded.
```
