### ISSUE TITLE
Cyipopt comptability with Firedrake

### ISSUE THREAD

**Issue by mim-GK** [mechmotum/cyipopt#260]
Hi, I am working on a topology optimisation problem in the context of stress and have been trying to run the following code within firedrake environment using Ipopt that uses cyipopt as a wrapper, my issue is that even though I have installed cyipopt using `pip install cyipopt` the error is as follows stating issues around NumPy compatibility which I am not sure what to do about as I am afraid if I try downgrading it according to the suggestions from output it might conflict with the rest of firedrake libraries. I have also tried `python -c "import cyipopt"` repeating the same error. Any help will be appreciated thank you.

Error:
```
> UserWarning: Unable to import recommended hash 'siphash24.siphash13', falling back to 'hashlib.sha256'. Run 'python3 -m pip install siphash24' to install the recommended hash.
> warn("Unable to import recommended hash 'siphash24.siphash13', "
> firedrake:WARNING OMP_NUM_THREADS is not set or is set to a value greater than 1, we suggest setting OMP_NUM_THREADS=1 to improve performance
> /Users/fire/firedrake/src/firedrake/firedrake/interpolation.py:385: FutureWarning: The use of interpolate to perform the numerical interpolation is deprecated.
> This feature will be removed very shortly.
> 
> Instead, import interpolate from the firedrake.__future__ module to update
> the interpolation's behaviour to return the symbolic ufl.Interpolate object associated
> with this interpolation.
> 
> You can then assemble the resulting object to get the interpolated quantity
> of interest. For example,
> 
> from firedrake.__future__ import interpolate
> ...
> 
> assemble(interpolate(expr, V))
> Alternatively, you can also perform other symbolic operations on the interpolation operator, such as taking
> the derivative, and then assemble the resulting form.
> 
> warnings.warn("""The use of interpolate to perform the numerical interpolation is deprecated.
> 
> A module that was compiled using NumPy 1.x cannot be run in
> NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
> versions of NumPy, modules must be compiled with NumPy 2.0.
> Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
> 
> If you are a user of the module, the easiest solution will be to
> downgrade to 'numpy<2' or try to upgrade the affected module.
> We expect that some modules will need time to support NumPy 2.
> 
> Traceback (most recent call last): File "/Users/fire/TopOpt.py", line 75, in
> solver = IPOPTSolver(problem, parameters=parameters)
> File "/Users/fire/firedrake/src/pyadjoint/pyadjoint/optimization/ipopt_solver.py", line 31, in init
> self.__build_ipopt_problem()
> File "/Users/fire/firedrake/src/pyadjoint/pyadjoint/optimization/ipopt_solver.py", line 37, in __build_ipopt_problem
> from pyadjoint.ipopt import cyipopt
> File "/Users/fire/firedrake/src/pyadjoint/pyadjoint/ipopt.py", line 11, in
> import cyipopt # noqa: F401
> File "/Users/fire/firedrake/lib/python3.11/site-packages/cyipopt/init.py", line 12, in
> from ipopt_wrapper import *
> Traceback (most recent call last):
> File "/Users/fire/firedrake/src/pyadjoint/pyadjoint/ipopt.py", line 11, in
> import cyipopt # noqa: F401
> ^^^^^^^^^^^^^^
> File "/Users/fire/firedrake/lib/python3.11/site-packages/cyipopt/init.py", line 12, in
> from ipopt_wrapper import *
> File "cyipopt/cython/ipopt_wrapper.pyx", line 1, in init ipopt_wrapper
> ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use 'numpy._import_array' to disable if you are certain you don't need it).
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/Users/fire/TopOpt.py", line 75, in
> solver = IPOPTSolver(problem, parameters=parameters)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/Users/fire/firedrake/src/pyadjoint/pyadjoint/optimization/ipopt_solver.py", line 31, in init
> self.__build_ipopt_problem()
> File "/Users/fire/firedrake/src/pyadjoint/pyadjoint/optimization/ipopt_solver.py", line 37, in __build_ipopt_problem
> from pyadjoint.ipopt import cyipopt
> File "/Users/fire/firedrake/src/pyadjoint/pyadjoint/ipopt.py", line 13, in
> raise ImportError("You need to install cyipopt. It is recommended to install IPOPT with HSL support!")
> ImportError: You need to install cyipopt. It is recommended to install IPOPT with HSL support!
```
Code:
```python
from firedrake import *
from firedrake.adjoint import *
import matplotlib.pyplot as plt
import numpy as np
from firedrake import (
    inner,
    dx,
    ds,
    sym,
    Constant
)

from pyadjoint import Control, ReducedFunctional, MinimizationProblem, IPOPTSolver
from firedrake.adjoint import UFLInequalityConstraint


continue_annotation()
# Create a unit square mesh with 10x10 cells
mesh = UnitSquareMesh(300, 100)
X = SpatialCoordinate(mesh)
F = 2000 #####
traction = Constant([0, -F])
p = Constant(3)
eps = Constant(1e-3)
# Define a function space on the mesh
W = FunctionSpace(mesh, "CG", 1) ####
V = VectorFunctionSpace(mesh, "CG", 2)


# Structure material properties
# Elasticity parameters
E = Constant(1e5)
nu = Constant(0.3)
mu = (E / (2 * (1 + nu))) 
lmbda = (E * nu / ((1 + nu) * (1 - 2 * nu)))

# Define boundary conditions
# Fixed left edge (x = 0)
bc = DirichletBC(V, Constant((0, 0)), 1)  # Clamped at the left edge associated with vector values

def forward(rho):
    v = TestFunction(V)
    u = TrialFunction(V)
    # Define the traction force (applied in the middle of the right edge)

    

    # Define E_rho based on SIMP method
    E_rho = eps + (E - eps) * rho**p

    lmbda = nu * E_rho / ((1 + nu) * (1 - 2 * nu))
    mu = E_rho / (2 * (1 + nu))

    L = inner(traction, v) * ds(2)

    # Variational problem setup
    a = 2*mu*inner(sym(grad(u)), sym(grad(v)))*dx + lmbda*div(u)*div(v)*dx
    
    u = Function(V, name="Displacement")
    solve(a == L, u, bc, solver_parameters={"pc_factor_mat_solver_type": "superlu_dist"})
    return u

# Set initial density and define the objective function
Vol = 0.5
rho = interpolate(Constant(Vol), W)
u = forward(rho)
J = assemble(inner(traction, u) * dx)####### could be 1 or dx
m = Control(rho)
Jhat = ReducedFunctional(J, m)
# Volume constraint
volume_constraint = UFLInequalityConstraint((Constant(Vol) - rho) * dx, m)

# Optimization setup
lb, ub = 0.0, 1.0
problem = MinimizationProblem(Jhat, bounds=(lb, ub), constraints=volume_constraint)
parameters = {"acceptable_tol": 1.0e-3, "maximum_iterations": 100}
solver = IPOPTSolver(problem, parameters=parameters)
rho_opt = solver.solve()

# PARAVIEW Results
results = File("newsolution.pvd")
results.parameters["flush_output"] = True
results.parameters["functions_share_mesh"] = True
results.write = (rho_opt, 0.)
results.write = (u, 0.)
```

**Comment by moorepants** [comment]
If you installed cyipopt using `pip install cyipopt` it should compile against whatever NumPy is associated with the python that ran Pip (i.e. pip and numpy in the same site packages directory). If that NumPy is < 2.0 and then you try to use cyipopt with NumPy >= 2.0, you'll get this warning.

Please report what OS you are using and the entire compilation output from the `pip install` command. Also report which NumPy is in the same environment as the pip you are using and which one is in the environment that firedrake is using.

The solution is likely that you need to compile cyipopt against NumPy >= 2.0.

**Comment by moorepants** [comment]
Having a quick look at this: https://www.firedrakeproject.org/download.html shows that firedrake has some kind of custom installation process that isn't through typical package management systems, so I'm not sure we can help you much here. If firedrake is running against a different python environment that cyipopt is installed in, I can imagine you'll have compatibility problems.

**Comment by moorepants** [comment]
Closing, as it does not seem to be a cyipopt issue. Reopen with more information if you think this is a cyipopt issue.
